# Generated by Django 5.0.4 on 2024-05-10 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("IDAC", models.IntegerField(primary_key=True, serialize=False)),
                ("NameAc", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Phone", models.CharField(max_length=100)),
                ("Username", models.CharField(max_length=100)),
                ("Pass", models.CharField(max_length=100)),
                ("Avatar", models.CharField(max_length=100)),
                ("NgaySinh", models.DateField()),
                ("DiaChi", models.CharField(max_length=100)),
                ("NgayTao", models.DateField()),
                ("GioiTinh", models.CharField(max_length=10)),
                ("Salt", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="DanhMucSanPham",
            fields=[
                (
                    "MaDanhMuc",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TenDanhMuc", models.CharField(max_length=100)),
                ("Publish", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LoaiSanPham",
            fields=[
                (
                    "MaLoaiSP",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TenLoaiSP", models.CharField(max_length=100)),
                ("SoLuong", models.IntegerField()),
                ("NgayTao", models.DateField()),
                ("NgayCapNhat", models.DateField()),
                ("NguoiTao", models.CharField(max_length=100)),
                ("NguoiCapNhat", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "MaMenu",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TenMenu", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("RoleID", models.IntegerField(primary_key=True, serialize=False)),
                ("RoleName", models.CharField(max_length=100)),
                ("Decription", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TrangThaiGiaoHang",
            fields=[
                (
                    "TransactStatusID",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("Status", models.CharField(max_length=100)),
                ("Decription", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DonDatHang",
            fields=[
                (
                    "MaDon",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("Deleted", models.IntegerField()),
                ("SDT", models.CharField(max_length=100)),
                ("TongTien", models.DecimalField(decimal_places=2, max_digits=10)),
                ("NgayDat", models.DateField()),
                ("NgayGiao", models.DateField()),
                ("DiaChi", models.CharField(max_length=100)),
                (
                    "IDAC",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "TransactStatusID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.trangthaigiaohang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DanhMucThuongHieu",
            fields=[
                (
                    "MaDanhMuc",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TenDanhMuc", models.CharField(max_length=100)),
                (
                    "MaMenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.menu"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="RoleID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.roles"
            ),
        ),
        migrations.CreateModel(
            name="SanPham",
            fields=[
                (
                    "MaSP",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("TenSP", models.CharField(max_length=255)),
                ("HinhAnh", models.CharField(max_length=100)),
                ("MoTa", models.TextField()),
                ("SoLuong", models.IntegerField()),
                ("GiaBan", models.DecimalField(decimal_places=2, max_digits=10)),
                ("GiaGiam", models.DecimalField(decimal_places=2, max_digits=10)),
                ("NguoiTao", models.CharField(max_length=100)),
                ("NgayTao", models.DateField()),
                ("NguoiCapNhat", models.CharField(max_length=100)),
                ("NgayCapNhat", models.DateField()),
                ("TrangThai", models.CharField(max_length=100)),
                (
                    "MaLoaiSP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.loaisanpham",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietDonHang",
            fields=[
                ("MaCTDH", models.IntegerField(primary_key=True, serialize=False)),
                ("SL", models.IntegerField()),
                ("Total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("GiaBan", models.DecimalField(decimal_places=2, max_digits=10)),
                ("GiaGiam", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "MaDon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dondathang",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sanpham"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SoLuong", models.PositiveIntegerField(default=1)),
                ("NgayTao", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "NguoiDung",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.account"
                    ),
                ),
                (
                    "SanPham",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sanpham"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThuongHieuSanPham",
            fields=[
                (
                    "MaThuongHieu",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("TenThuongHieu", models.CharField(max_length=100)),
                (
                    "MaDanhMuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.danhmucthuonghieu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChiTietSanPham",
            fields=[
                (
                    "MaChiTietSP",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("XuatXu", models.CharField(max_length=100)),
                ("DongMay", models.CharField(max_length=100)),
                ("ChatLieu", models.CharField(max_length=100)),
                ("PhongCach", models.CharField(max_length=100)),
                ("DoiTuong", models.CharField(max_length=100)),
                (
                    "MaDanhMuc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.danhmucsanpham",
                    ),
                ),
                (
                    "MaSP",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sanpham"
                    ),
                ),
                (
                    "MaThuongHieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.thuonghieusanpham",
                    ),
                ),
            ],
        ),
    ]
