# Generated by Django 5.0.4 on 2024-05-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaisanpham",
            name="NgayCapNhat",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="loaisanpham",
            name="NgayTao",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sanpham",
            name="NgayTao",
            field=models.DateField(auto_now_add=True),
        ),
    ]
