# Generated by Django 5.0.4 on 2024-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_loaisanpham_ngaycapnhat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="NgayCapNhat",
            field=models.DateField(blank=True, null=True),
        ),
    ]
