# Generated by Django 5.0.4 on 2024-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_sanpham_ngaycapnhat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thuonghieusanpham",
            name="MaThuongHieu",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
