# Generated by Django 5.0.4 on 2024-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_thuonghieusanpham_mathuonghieu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="IDAC",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
