# Generated by Django 5.0.4 on 2024-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_account_ngaytao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="HinhAnh",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
