# Generated by Django 5.0.4 on 2024-05-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_sanpham_hinhanh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="HinhAnh",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
