# Generated by Django 5.0.4 on 2024-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_sanpham_hinhanh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sanpham",
            name="HinhAnh",
            field=models.CharField(max_length=255),
        ),
    ]
