# Generated by Django 5.0.4 on 2024-05-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_sanpham_hinhanh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loaisanpham",
            name="NgayCapNhat",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loaisanpham",
            name="NguoiCapNhat",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
