# Generated by Django 5.0.4 on 2024-05-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_loaisanpham_ngaycapnhat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondathang",
            name="MaDon",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
