# Generated by Django 5.0.4 on 2024-05-23 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_dondathang_madon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondathang",
            name="TransactStatusID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.trangthaigiaohang",
            ),
        ),
    ]
