# Generated by Django 5.0.4 on 2024-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_dondathang_idac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondathang",
            name="Deleted",
            field=models.IntegerField(default=0),
        ),
    ]
