# Generated by Django 5.0.4 on 2024-05-23 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_dondathang_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondathang",
            name="NgayDat",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dondathang",
            name="NgayGiao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
