# Generated by Django 5.0.4 on 2024-05-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_dondathang_ngaydat_alter_dondathang_ngaygiao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dondathang",
            name="TongTien",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
