# Generated by Django 5.0.4 on 2024-05-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_dondathang_tongtien"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="NgaySinh",
            field=models.DateField(blank=True, null=True),
        ),
    ]
