# Generated by Django 5.0.4 on 2024-05-23 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_account_ngaysinh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="SoLuong",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="chitietdonhang",
            name="MaCTDH",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="dondathang",
            name="IDAC",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.account"
            ),
        ),
        migrations.AlterField(
            model_name="dondathang",
            name="TongTien",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
