# Generated by Django 5.2 on 2025-05-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_cart_soluong_alter_chitietdonhang_mactdh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='HinhAnh',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
